export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="agnoster"
plugins=(git)
source $ZSH/oh-my-zsh.sh

HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=100000
unsetopt beep

# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/svet/.zshrc'

# Autojump
[[ -s /home/svet/.autojump/etc/profile.d/autojump.sh ]] && source /home/svet/.autojump/etc/profile.d/autojump.sh
autoload -U compinit && compinit -u


export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

alias update="sudo pacman -Syu --noconfirm"

